### ISSUE TITLE
Odd roots don't evaluate for negative numbers

### ISSUE THREAD

**Issue by Belegestel** [leonhma/obsidian-functionplot#137]
### What happened?

I tried getting a plot for f(x) = x^(1/3). Everything computed correctly... But only for positive numbers. Cubic roots (odd roots in general) are defined for negative numbers, therefore they also should be displayed.

### Please confirm

- [X] I have checked that I am using the latest version of the plugin released.
- [X] I have searched for similar issues, but found none.

### Any ideas?

Most likely the power operation terminates on the negative numbers by default, without checking if the value is actually computable. It's likely that the bug is within the evaluation function, precisely - in the power function.

### Additional info

![obraz](https://github.com/leonhma/obsidian-functionplot/assets/76164171/534e69af-cbe5-4ac6-a8f6-55c2da7059fc)
```functionplot
---
bounds: [-6,6,-4,4]
disableZoom: true
grid: true
---
f(x) = x^(1/3)
```

**Comment by leomanga** [comment]
Hello,
the first thing you can do is to use: 
`y = sign(x) * pow(abs(x), 1/3)`
This is a problem of the functions in the Math object.

**Comment by leonhma** [comment]
Closing this, since it is an upstream issue (?apparently, I don't know much about imaginary numbers...)

**Comment by leomanga** [comment]
> Closing this, since it is an upstream issue (?apparently, I don't know much about imaginary numbers...)

In this case, you don't need the imaginary numbers. 
You can calculate an odd root of a negative number(-8^(1/3) = -2), but the Math object (I don't know why) don't work very well.

Here you can find some solutions and explanations:

> https://stackoverflow.com/questions/12810765/calculating-cubic-root-for-negative-number

**Comment by leonhma** [comment]
I looked some more and [this post](https://math.stackexchange.com/a/4067924) seems to give a good explanation. Apparently this is deeply rooted in lower level code and because of this I honestly wouldn't hold my breath for this to be a feature. I suggest using one of the workarounds provided.
