### ISSUE TITLE
Inverse fuction like arcsin, arcos are not running 

### ISSUE THREAD

**Issue by momot04** [leonhma/obsidian-functionplot#138]
### What happened?

Inverse functions don't work, could it be that I'm doing the notation wrong?

### Please confirm

- [X] I have checked that I am using the latest version of the plugin released.
- [X] I have searched for similar issues, but found none.

**Comment by leonhma** [comment]
Could you provide me with the notation you are using?

**Comment by momot04** [comment]
I used notations like: arcsin(x), sin^-1, sin^(-1), sin^{-1}. I've tried
them all. Which one do you tell me to use? A thousand thanks

Il Gio 2 Nov 2023, 13:45 Leonhard Masche ***@***.***> ha
scritto:

**Comment by leonhma** [comment]
Have you already taken a look at [this page](https://github.com/leonhma/obsidian-functionplot/wiki/Supported-function-syntax) in the wiki? If you click on the `all the functions and constants supported by Math` link, you'll be taken to a list of some of the more advanced functions included.
This includes:
* `acos`
* `atan`
* `asin`
* ...

**Comment by momot04** [comment]
Thank you your work is very good.
Thanks for sharing it.
I will donate later.
Thank you again

Il Gio 2 Nov 2023, 14:19 Leonhard Masche ***@***.***> ha
scritto:
