### ISSUE TITLE
[FR]: Increase readabilty

### ISSUE THREAD

**Issue by hauselin** [leonhma/obsidian-functionplot#28]
### What's your feature?

The plots, axis labels, and font sizes are relatively small and difficult to read. It would be nice to implement one or more of the following to increase readability (see discussion #25):
- increase default font size (or option to change size)
- increase default line thickness (or option to change line thickness)
- option to change color of lines

Thanks!

**Comment by leonhma** [comment]
Just released `1.2.0` with a new settings page and the ability to style the plot. The documentation and wiki entries will follow soon.
