### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by leonhma** [leonhma/obsidian-functionplot#36]
### Discussed in https://github.com/leonhma/obsidian-functionplot/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **GavinLau15** September 11, 2022</sup>
Hi,

I recently installed this plugin you made, but when I press ctrl + p to enter my command pallete and try to type the command to create a graph, the option simply does not pop up, any help would be appreciated.</div>

**Comment by leonhma** [comment]
Okay, that's weird. I just checked and the release works fine for me. I downloaded the plugin, enabled it and everything worked.

Can you confirm some things for me?

- Does the tab 'Obsidian Functionplot' shows up in the settings?
- What is the version of obsidian you are using?
- What other plugins are installed?
- Did you install from the community plugins or via git?
- What platform are you on?
- If possible can you disable the plugin, open the chrome devtools (on windows and linux press Ctrl+Shift+i), switch to the console tab, enable the plugin and send me a screenshot of the console output or copy/paste it.

Again, I don't really know what's happening here. Maybe some of this info will help reproducing the issue.

**Comment by Leo-Zarni01** [comment]
Try opening the command palette while you are in editing mode and not reading mode. I had a similar issue but doing that seems to resolve it.

**Comment by leonhma** [comment]
Considering this resolved due to inactivity.
